name: A workflow for my Hello World App
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup network
        run: |
          docker network create --driver bridge devops
          docker pull mongo
          docker run -d --name mongo-dbserver --network devops mongo
      - name: Compile with Maven
        run: mvn package
      - name: Build
        run: docker build -t devops .
      - name: Run image
        run: docker run --network devops --name devopscontainer devops
      - name: view logs
        run: docker logs devopscontainer
